DROP DATABASE IF EXISTS SAT;
CREATE DATABASE SAT;
USE SAT;

CREATE TABLE ENDERECO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CEP CHAR(9) NOT NULL,
    BAIRRO VARCHAR(200) NOT NULL,
    LOGRADOURO VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    
    UNIQUE INDEX(BAIRRO, LOGRADOURO, NUMERO)
);

CREATE TABLE PESSOA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    RG CHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW(),
    SEXO ENUM('MASCULINO', 'FEMININO', 'OUTRO'),
    ENDERECO_ID INT,
    
    FOREIGN KEY(ENDERECO_ID) REFERENCES ENDERECO(ID)
		ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CONTATO (
	PESSOA_ID INT NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    TELEFONE VARCHAR(25) NOT NULL,
  
	FOREIGN KEY(PESSOA_ID) REFERENCES PESSOA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE UNIDADE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL UNIQUE,
    QUANTIDADE_EQUIPAMENTOS INT NOT NULL,
    ENDERECO_ID INT NOT NULL,
    
    FOREIGN KEY(ENDERECO_ID) REFERENCES ENDERECO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE USUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(50) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    PESSOA_ID INT NOT NULL,
    
    FOREIGN KEY(PESSOA_ID) REFERENCES PESSOA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
    #CHECK (LENGTH(SENHA) >= 8)
);

CREATE TABLE COORDENADOR (
    USUARIO_ID INT PRIMARY KEY,
    
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COORDENADOR_UNIDADE (
	COORDENADOR_ID INT PRIMARY KEY,
    UNIDADE_ID INT NOT NULL UNIQUE,
    
    FOREIGN KEY(COORDENADOR_ID) REFERENCES COORDENADOR(USUARIO_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(UNIDADE_ID) REFERENCES UNIDADE(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COORDENADOR_GERAL (
	COORDENADOR_ID INT PRIMARY KEY,
    
    FOREIGN KEY(COORDENADOR_ID) REFERENCES COORDENADOR(USUARIO_ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INSTRUTOR (
    USUARIO_ID INT PRIMARY KEY,
    
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TURMA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(50) NOT NULL UNIQUE,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    TURNO ENUM('MATUTINO', 'VESPERTINO', 'NOTURNO') NOT NULL,
    INSTRUTOR_ID INT NOT NULL,
    UNIDADE_ID INT NOT NULL,
    
    FOREIGN KEY(INSTRUTOR_ID) REFERENCES INSTRUTOR(USUARIO_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(UNIDADE_ID) REFERENCES UNIDADE(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MODULO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL UNIQUE,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE TURMA_MODULO (
	MODULO_ID INT NOT NULL,
	TURMA_ID INT NOT NULL,
    
    PRIMARY KEY(MODULO_ID, TURMA_ID),
    FOREIGN KEY(TURMA_ID) REFERENCES TURMA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(MODULO_ID) REFERENCES MODULO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUNO (
    USUARIO_ID INT PRIMARY KEY,
    TURMA_ID INT NOT NULL,
    
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(TURMA_ID) REFERENCES TURMA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BOLETIM (
	ALUNO_ID INT NOT NULL,
    MODULO_ID INT NOT NULL,
    NOTA INT NOT NULL,
    
    PRIMARY KEY(ALUNO_ID, MODULO_ID),
    FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(USUARIO_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(MODULO_ID) REFERENCES MODULO(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AULA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO TEXT NOT NULL,
    `DATA` DATE NOT NULL, 
    TURMA_ID INT NOT NULL,
    
    FOREIGN KEY(TURMA_ID) REFERENCES TURMA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REGISTRO_AULA (
	ALUNO_ID INT NOT NULL,
    AULA_ID INT NOT NULL,
    PRESENTE BOOLEAN NOT NULL,
    
    PRIMARY KEY(ALUNO_ID, AULA_ID),
    FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(USUARIO_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(AULA_ID) REFERENCES AULA(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO ENDERECO(CEP, BAIRRO, LOGRADOURO, NUMERO) VALUES
('59291-631', 'Centro', 'Rua', '379'),
('59290-000', 'Conjunto Brasil', 'Conjunto', '123');
INSERT INTO PESSOA(NOME, CPF, RG, DATA_NASCIMENTO, SEXO, ENDERECO_ID) VALUES
('Lucas do Nascimento Ribeiro', '111.111.111-11', '000.000.000', '2000-07-23', 'MASCULINO', 1),
('Maria Isabel da Cruz Pinheiro', '222.222.222-22', '111.111.111', '2001-05-24', 'FEMININO', 2),
('Vitória Beatriz Lima de Sá', '333.333.333-33', '222.222.222', '2001-09-09', 'FEMININO', 2);
INSERT INTO CONTATO(PESSOA_ID, EMAIL, TELEFONE) VALUES 
((SELECT ID FROM PESSOA WHERE CPF = '111.111.111-11'), 'lucasnascimentoribeiro13@gmail.com', '+55 084 9-8852-3780'),
((SELECT ID FROM PESSOA WHERE CPF = '222.222.222-22'), 'mabellcruz2001@gmail.com', '+55 084 9-8888-8888'),
((SELECT ID FROM PESSOA WHERE CPF = '333.333.333-33'), 'vitoriabeatriz.123@gmail.com', '+55 084 9-9999-9999')
;

INSERT INTO USUARIO(MATRICULA, SENHA, PESSOA_ID) VALUES 
('20161164010023', 'ifrn.2019', (SELECT ID FROM PESSOA WHERE CPF = '111.111.111-11')),
('20161164010015', 'ifrn.2019', (SELECT ID FROM PESSOA WHERE CPF = '222.222.222-22')),
('20161164010012', 'ifrn.2019', (SELECT ID FROM PESSOA WHERE CPF = '333.333.333-33'));

INSERT INTO COORDENADOR(USUARIO_ID) VALUES ((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '111.111.111-11'));
INSERT INTO COORDENADOR_GERAL(COORDENADOR_ID) VALUES((SELECT C.USUARIO_ID FROM COORDENADOR C JOIN USUARIO U ON C.USUARIO_ID = U.ID JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '111.111.111-11'));

INSERT INTO INSTRUTOR(USUARIO_ID) VALUES ((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '222.222.222-22')), ((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '111.111.111-11'));
INSERT INTO UNIDADE(NOME, QUANTIDADE_EQUIPAMENTOS, ENDERECO_ID) VALUES ('Unidade do Centro', 15, 1);
INSERT INTO TURMA(CODIGO, DATA_INICIO, DATA_FIM, TURNO, INSTRUTOR_ID, UNIDADE_ID) VALUES 
('CENTRO.2019.MATU', '2019-06-23', '2019-12-23', 'MATUTINO', (SELECT I.USUARIO_ID FROM INSTRUTOR I JOIN USUARIO U ON U.ID = I.USUARIO_ID JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE CPF = '222.222.222-22'), 1);
INSERT INTO MODULO(TITULO, DESCRICAO) VALUES ('Sistemas Operacionais', 'Aprendendo a lidar com os diversos Sistemas Operacionais, como Windows, Linux e MacOS');
INSERT INTO MODULO(TITULO, DESCRICAO) VALUES ('Editores de Texto', 'Aprendendo a usar o Word e o Notepad');
INSERT INTO TURMA_MODULO(TURMA_ID, MODULO_ID) VALUES ((SELECT ID FROM TURMA WHERE CODIGO = 'CENTRO.2019.MATU'), (SELECT ID FROM MODULO WHERE TITULO = 'Sistemas Operacionais'));


INSERT INTO ALUNO(USUARIO_ID, TURMA_ID) VALUES ((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '333.333.333-33'), 1);


INSERT INTO AULA(TURMA_ID, DESCRICAO, `DATA`) VALUES ((SELECT ID FROM TURMA WHERE CODIGO = 'CENTRO.2019.MATU'), 'Aula de Windows', NOW());
INSERT INTO AULA(TURMA_ID, DESCRICAO, `DATA`) VALUES ((SELECT ID FROM TURMA WHERE CODIGO = 'CENTRO.2019.MATU'), 'Aula de Linux', NOW());
INSERT INTO REGISTRO_AULA(AULA_ID, ALUNO_ID, PRESENTE) VALUES (1, (SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '333.333.333-33'), TRUE);
INSERT INTO REGISTRO_AULA(AULA_ID, ALUNO_ID, PRESENTE) VALUES (2, (SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '333.333.333-33'), FALSE);

INSERT INTO BOLETIM(ALUNO_ID, MODULO_ID, NOTA) VALUES 
((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '333.333.333-33'), (SELECT ID FROM MODULO WHERE TITULO = 'Sistemas Operacionais'), 100),
((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '333.333.333-33'), (SELECT ID FROM MODULO WHERE TITULO = 'Editores de Texto'), 50)
;

INSERT INTO COORDENADOR(USUARIO_ID) VALUES ((SELECT U.ID FROM USUARIO U JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '222.222.222-22'));
INSERT INTO COORDENADOR_UNIDADE(COORDENADOR_ID, UNIDADE_ID) VALUES((SELECT C.USUARIO_ID FROM COORDENADOR C JOIN USUARIO U ON C.USUARIO_ID = U.ID JOIN PESSOA P ON P.ID = U.PESSOA_ID WHERE P.CPF = '222.222.222-22'), 1);



SELECT * FROM coordenador_unidade;	




