USE SAT;
SELECT * FROM PESSOA;

SELECT P.NOME, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID;

#TODOS USUÁRIOS
SELECT P.ID, P.NOME, U.MATRICULA, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID
JOIN USUARIO U ON U.PESSOA_ID = P.ID
ORDER BY P.NOME;

#TODOS ALUNOS
SELECT P.ID, P.NOME, U.MATRICULA, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO, T.CODIGO
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID
JOIN USUARIO U ON U.PESSOA_ID = P.ID
JOIN ALUNO A ON A.USUARIO_ID = U.ID
JOIN TURMA T ON T.ID = A.TURMA_ID
ORDER BY T.CODIGO, P.NOME;

#TODOS INSTRUTORES
SELECT P.ID, P.NOME, U.MATRICULA, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO, UN.NOME AS UNIDADE, 
(SELECT DISTINCT COUNT(*) FROM TURMA T WHERE T.INSTRUTOR_ID = I.USUARIO_ID) AS 'QUANTIDADE DE TURMAS'
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID
JOIN USUARIO U ON U.PESSOA_ID = P.ID
JOIN INSTRUTOR I ON I.USUARIO_ID = U.ID
JOIN UNIDADE UN ON UN.ID = I.UNIDADE_ID
ORDER BY P.NOME;

#TODOS COORDENADORES DE UNIDADE
SELECT P.ID, P.NOME, U.MATRICULA, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO, UN.NOME AS UNIDADE
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID
JOIN USUARIO U ON U.PESSOA_ID = P.ID
JOIN COORDENADOR_UNIDADE CU ON CU.COORDENADOR_ID = U.ID
JOIN UNIDADE UN ON UN.ID = CU.UNIDADE_ID
ORDER BY P.NOME;

#TODOS COORDENADORES GERAIS
SELECT P.ID, P.NOME, U.MATRICULA, P.CPF, P.RG, P.DATA_NASCIMENTO, P.SEXO, E.BAIRRO, E.LOGRADOURO, E.NUMERO
FROM PESSOA P
JOIN ENDERECO E ON E.ID = P.ENDERECO_ID
JOIN USUARIO U ON U.PESSOA_ID = P.ID
JOIN COORDENADOR_GERAL CG ON CG.COORDENADOR_ID = U.ID
ORDER BY P.NOME;

#TODAS UNIDADES
SELECT U.ID, U.NOME, U.QUANTIDADE_EQUIPAMENTOS, E.BAIRRO, E.LOGRADOURO, E.NUMERO
FROM UNIDADE U
JOIN ENDERECO E ON E.ID = U.ENDERECO_ID;
